-------------------------------------------------------------------------------
Test set: Sign up
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 33.718 s <<< FAILURE! - in Sign up
Fill In details of Volunteer Sign up using DataTable(Sign up)  Time elapsed: 33.718 s  <<< ERROR!
org.openqa.selenium.NoSuchSessionException: 
invalid session id
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'A-PC0ZSJ1M', ip: '10.18.33.181', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_291'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 95.0.4638.69, chrome: {chromedriverVersion: 95.0.4638.69 (6a1600ed572fe..., userDataDir: C:\Users\SAURAB~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:50702}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c861f1bafad1c51477234430fb3ff441
*** Element info: {Using=css selector, value=frame[name='frame\-one1434677811'],iframe[name='frame\-one1434677811']}

Fill In details of Volunteer Sign up using DataTable(Sign up)  Time elapsed: 0 s  <<< ERROR!
org.openqa.selenium.WebDriverException: 
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:34592
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'A-PC0ZSJ1M', ip: '10.18.33.181', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_291'
Driver info: driver.version: RemoteWebDriver
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:34592
Caused by: java.net.ConnectException: Connection refused: connect

